services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: securebank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/securebank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: bXlzdXBlcnNlY3JldGtleWZvcmp3dHRva2VuZ2VuZXJhdGlvbm1pbjI1NmJpdHM=
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_EXPIRATION: 86400000

  frontend:
    build: ./securebank-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: